// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: demo/data.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarTime     string             `protobuf:"bytes,1,opt,name=BarTime,proto3" json:"BarTime,omitempty"`
	InstID      string             `protobuf:"bytes,2,opt,name=InstID,proto3" json:"InstID,omitempty"`
	IndiDataMap map[string]float64 `protobuf:"bytes,3,rep,name=IndiDataMap,proto3" json:"IndiDataMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *BarM) Reset() {
	*x = BarM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarM) ProtoMessage() {}

func (x *BarM) ProtoReflect() protoreflect.Message {
	mi := &file_demo_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarM.ProtoReflect.Descriptor instead.
func (*BarM) Descriptor() ([]byte, []int) {
	return file_demo_data_proto_rawDescGZIP(), []int{0}
}

func (x *BarM) GetBarTime() string {
	if x != nil {
		return x.BarTime
	}
	return ""
}

func (x *BarM) GetInstID() string {
	if x != nil {
		return x.InstID
	}
	return ""
}

func (x *BarM) GetIndiDataMap() map[string]float64 {
	if x != nil {
		return x.IndiDataMap
	}
	return nil
}

type BarS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarTime       string    `protobuf:"bytes,1,opt,name=BarTime,proto3" json:"BarTime,omitempty"`
	InstID        string    `protobuf:"bytes,2,opt,name=InstID,proto3" json:"InstID,omitempty"`
	IndiDataSlice []float64 `protobuf:"fixed64,3,rep,packed,name=IndiDataSlice,proto3" json:"IndiDataSlice,omitempty"`
}

func (x *BarS) Reset() {
	*x = BarS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarS) ProtoMessage() {}

func (x *BarS) ProtoReflect() protoreflect.Message {
	mi := &file_demo_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarS.ProtoReflect.Descriptor instead.
func (*BarS) Descriptor() ([]byte, []int) {
	return file_demo_data_proto_rawDescGZIP(), []int{1}
}

func (x *BarS) GetBarTime() string {
	if x != nil {
		return x.BarTime
	}
	return ""
}

func (x *BarS) GetInstID() string {
	if x != nil {
		return x.InstID
	}
	return ""
}

func (x *BarS) GetIndiDataSlice() []float64 {
	if x != nil {
		return x.IndiDataSlice
	}
	return nil
}

type MapBarM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapBarM map[string]*BarM `protobuf:"bytes,1,rep,name=MapBarM,proto3" json:"MapBarM,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // map in
}

func (x *MapBarM) Reset() {
	*x = MapBarM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapBarM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBarM) ProtoMessage() {}

func (x *MapBarM) ProtoReflect() protoreflect.Message {
	mi := &file_demo_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBarM.ProtoReflect.Descriptor instead.
func (*MapBarM) Descriptor() ([]byte, []int) {
	return file_demo_data_proto_rawDescGZIP(), []int{2}
}

func (x *MapBarM) GetMapBarM() map[string]*BarM {
	if x != nil {
		return x.MapBarM
	}
	return nil
}

type MapBarS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapBarS map[string]*BarS `protobuf:"bytes,1,rep,name=MapBarS,proto3" json:"MapBarS,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // map in
}

func (x *MapBarS) Reset() {
	*x = MapBarS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapBarS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBarS) ProtoMessage() {}

func (x *MapBarS) ProtoReflect() protoreflect.Message {
	mi := &file_demo_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBarS.ProtoReflect.Descriptor instead.
func (*MapBarS) Descriptor() ([]byte, []int) {
	return file_demo_data_proto_rawDescGZIP(), []int{3}
}

func (x *MapBarS) GetMapBarS() map[string]*BarS {
	if x != nil {
		return x.MapBarS
	}
	return nil
}

var File_demo_data_proto protoreflect.FileDescriptor

var file_demo_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x04, 0x42, 0x61, 0x72, 0x4d,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x42, 0x61, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x73, 0x74,
	0x49, 0x44, 0x12, 0x3d, 0x0a, 0x0b, 0x49, 0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61,
	0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x42,
	0x61, 0x72, 0x4d, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x49, 0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61,
	0x70, 0x1a, 0x3e, 0x0a, 0x10, 0x49, 0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x5e, 0x0a, 0x04, 0x42, 0x61, 0x72, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6e, 0x73, 0x74, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49,
	0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x0d, 0x49, 0x6e, 0x64, 0x69, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x4d, 0x12, 0x34, 0x0a,
	0x07, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x4d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x4d, 0x2e, 0x4d, 0x61,
	0x70, 0x42, 0x61, 0x72, 0x4d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x42,
	0x61, 0x72, 0x4d, 0x1a, 0x46, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x4d, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x42, 0x61, 0x72, 0x4d,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x87, 0x01, 0x0a, 0x07,
	0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x53, 0x12, 0x34, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x42, 0x61,
	0x72, 0x53, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x53, 0x2e, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x53, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x53, 0x1a, 0x46, 0x0a,
	0x0c, 0x4d, 0x61, 0x70, 0x42, 0x61, 0x72, 0x53, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x42, 0x61, 0x72, 0x53, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x64, 0x65, 0x6d, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo_data_proto_rawDescOnce sync.Once
	file_demo_data_proto_rawDescData = file_demo_data_proto_rawDesc
)

func file_demo_data_proto_rawDescGZIP() []byte {
	file_demo_data_proto_rawDescOnce.Do(func() {
		file_demo_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_data_proto_rawDescData)
	})
	return file_demo_data_proto_rawDescData
}

var file_demo_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_demo_data_proto_goTypes = []interface{}{
	(*BarM)(nil),    // 0: demo.BarM
	(*BarS)(nil),    // 1: demo.BarS
	(*MapBarM)(nil), // 2: demo.MapBarM
	(*MapBarS)(nil), // 3: demo.MapBarS
	nil,             // 4: demo.BarM.IndiDataMapEntry
	nil,             // 5: demo.MapBarM.MapBarMEntry
	nil,             // 6: demo.MapBarS.MapBarSEntry
}
var file_demo_data_proto_depIdxs = []int32{
	4, // 0: demo.BarM.IndiDataMap:type_name -> demo.BarM.IndiDataMapEntry
	5, // 1: demo.MapBarM.MapBarM:type_name -> demo.MapBarM.MapBarMEntry
	6, // 2: demo.MapBarS.MapBarS:type_name -> demo.MapBarS.MapBarSEntry
	0, // 3: demo.MapBarM.MapBarMEntry.value:type_name -> demo.BarM
	1, // 4: demo.MapBarS.MapBarSEntry.value:type_name -> demo.BarS
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_demo_data_proto_init() }
func file_demo_data_proto_init() {
	if File_demo_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapBarM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapBarS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_data_proto_goTypes,
		DependencyIndexes: file_demo_data_proto_depIdxs,
		MessageInfos:      file_demo_data_proto_msgTypes,
	}.Build()
	File_demo_data_proto = out.File
	file_demo_data_proto_rawDesc = nil
	file_demo_data_proto_goTypes = nil
	file_demo_data_proto_depIdxs = nil
}
